name: "Check project release"

on:
  workflow_call:
    outputs:
      project_num:
        description: "The project number (e.g. 1, 2, 3a, 3b, or 4)."
        value: ${{ jobs.check_release.outputs.project_num }}
         
      project_ver:
        description: "The project version (e.g. v1.0.0)."
        value: ${{ jobs.check_release.outputs.project_ver }}
        
jobs:
  check_release:
    name: "Release Number"
    runs-on: ubuntu-latest
    outputs:
      project_num: ${{ steps.hello_world.outputs.project_num }}
      project_ver: ${{ steps.hello_world.outputs.project_ver }}
    steps:
      - name: "Hello world"
        id: hello_world
        run: |
          echo "Hello world"
          echo "::set-output name=project_num::1"
          echo "::set-output name=project_ver::v1.0.0"

  check_compile:
    name: "Code Compiles"
    runs-on: ubuntu-latest
    needs: check_release
    steps:
      - name: "Hello world"
        run: |
          echo "Hello world"
          echo "actor: ${{ github.actor }}"
          echo "ref: ${{ github.ref }}"
          echo "ref_type: ${{ github.ref_type }}"
          echo "repository: ${{ github.repository }}"
          echo "event: ${{ toJson(github.event) }}"
  
  check_source_warnings:
    name: "Code Warnings"
    runs-on: ubuntu-latest
    needs: check_compile
    steps:
      - name: "Hello world"
        run: echo "Hello world"

  check_javadoc_warnings:
    name: "Javadoc Warnings"
    runs-on: ubuntu-latest
    needs: check_compile
    steps:
      - name: "Hello world"
        run: echo "Hello world"

  check_tests:
    name: "JUnit Tests"
    runs-on: ubuntu-latest
    needs: check_compile
    steps:
      - name: "Hello world"
        run: echo "Hello world"

  check_code_style:
    name: "Code Style"
    runs-on: ubuntu-latest
    needs: check_compile
    steps:
      - name: "Hello world"
        run: echo "Hello world"
